version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run: make test bin
  report:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: make test
      - run: ./cc-test-reporter after-build --exit-code $? -p github.com/moxspec/moxspec-ocpsel/

workflows:
  build:
    jobs:
      - build:
          context: moxspec
      - report:
          context: moxspec
          requires:
            - build
          filters:
            branches:
              only: main
